name = "psychological_blue_mouse-17d2"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "psychological_blue_mouse-17d2_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "psychological_blue_mouse-17d2.wasm"
command = "npm run build:release"
